### ISSUE TITLE
After Inserting New Row it throws---Error: Unhandled rejection Error: mysql-model: No row inserted.

### ISSUE THREAD

**Issue by sunilpoojari** [michalkow/node-mysql-backbone#2]
Even after record is inserted in the mysql database/table the code/function throws an error while entering new rows into table.

Error:
Unhandled rejection Error: mysql-model: No row inserted.
    at Query.<anonymous> (D:\ExpressJS\node_modules\mysql-backbone\mysql-model.js:38:41)
    at Query.<anonymous> (D:\ExpressJS\node_modules\mysql\lib\Connection.js:525:10)
    at Query._callback (D:\ExpressJS\node_modules\mysql\lib\Connection.js:491:16)
    at Query.Sequence.end (D:\ExpressJS\node_modules\mysql\lib\protocol\sequences\Sequence.js:83:24)
    at Query._handleFinalResultPacket (D:\ExpressJS\node_modules\mysql\lib\protocol\sequences\Query.js:139:8)
    at Query.OkPacket (D:\ExpressJS\node_modules\mysql\lib\protocol\sequences\Query.js:72:10)
    at Protocol._parsePacket (D:\ExpressJS\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (D:\ExpressJS\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (D:\ExpressJS\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (D:\ExpressJS\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (D:\ExpressJS\node_modules\mysql\lib\Connection.js:91:28)
    at Socket.<anonymous> (D:\ExpressJS\node_modules\mysql\lib\Connection.js:525:10)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)

**Comment by sunilpoojari** [comment]
You need to at least one attribute with auto-increment, in-order to get insertId from the mysql database, 
insertId- It is a value returned by mysql in results json response.
Michal has used insertId for checking if record is inserted or not.
If that is 0 then these errors are thrown.
To solve this you need to have at least one attribute with auto-increment value.
