### ISSUE TITLE
users.fetch()

### ISSUE THREAD

**Issue by amolc** [michalkow/node-mysql-backbone#3]
When I try to fetch records without any parameters, it gives me an error.

users.fetch()
    .then(function(result){
      res.jsonp(result);
    })
    .catch(function(err) {
      console.log(err);
      res.jsonp(err);
		});

This gives me an error - 

Error: mysql-model: No id passed or set
    at /Users/mac/2019/api2/node_modules/mysql-backbone/mysql-model.js:12:20
    at Promise._execute (/Users/mac/2019/api2/node_modules/bluebird/js/release/debuggability.js:384:9)
    at Promise._resolveFromExecutor (/Users/mac/2019/api2/node_modules/bluebird/js/release/promise.js:518:18)
    at new Promise (/Users/mac/2019/api2/node_modules/bluebird/js/release/promise.js:103:10)
    at child.fetch (/Users/mac/2019/api2/node_modules/mysql-backbone/mysql-model.js:11:10)
    at exports.getallUser (/Users/mac/2019/api2/api/user.js:43:11)
    at Layer.handle [as handle_request] (/Users/mac/2019/api2/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/mac/2019/api2/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/mac/2019/api2/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/mac/2019/api2/node_modules/express/lib/router/layer.js:95:5)
    at /Users/mac/2019/api2/node_modules/express/lib/router/index.js:281:22
    at param (/Users/mac/2019/api2/node_modules/express/lib/router/index.js:354:14)
    at param (/Users/mac/2019/api2/node_modules/express/lib/router/index.js:365:14)
    at Function.process_params (/Users/mac/2019/api2/node_modules/express/lib/router/index.js:410:3)
    at next (/Users/mac/2019/api2/node_modules/express/lib/router/index.js:275:10)
    at SendStream.error (/Users/mac/2019/api2/node_modules/serve-static/index.js:121:7)

**Comment by michalkow** [comment]
It looks to me like you are using `mysqlBackbone.Model` to create `users` when you should be using `mysqlBackbone.Collection`
